language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

script:
  - go get ./...
  - go test ./recorder/...
  - go test ./replayer/...
  - cd example && go build -tags="recorder" && go build -tags="replayer" -gcflags="all=-N -l"

