language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

before_install:
    - curl https://raw.githubusercontent.com/didi/sharingan-go/recorder/install/go1.13 | sh

script:
  - go get ./...
  - go test ./recorder/...
  - go test ./replayer/...

